### ISSUE TITLE
Manuelles Anlegen Mi Devices geht nicht

### ISSUE THREAD

**Issue by DarthWeber** [Nall-chan/Xiaomi#2]
Hi, das manuelle Anlegen von Mi Devices geht auch nicht mit meinem IPS, siehe #1 
Sind Issues denn schon erwünscht?

**Comment by Nall-chan** [comment]
Manuell wird schwer. Mit dem neuem Update wird die Device ID (did) benötigt.
Update ist online, welches diverse Fehler beim anlegen von Instanzen behebt.
Einfach ist für den Anfang sonst Discord :)

**Comment by DarthWeber** [comment]
Super, jetzt geht es und alle Werte werden ausgelesen. Was nocht nicht geht, ist das Schalten: Jegliche Aktion macht (im Testcenter getestet):

`Konnte nicht schalten

Fatal error: Uncaught TypeError: Argument 2 passed to XiaomiMiDevice::WriteValue() must be an instance of mixed, bool given, called in /var/lib/symcon/modules/.store/de.nall.chan.xiaomi/Xiaomi Mi Device/module.php on line 184 and defined in /var/lib/symcon/modules/.store/de.nall.chan.xiaomi/Xiaomi Mi Device/module.php:304
Stack trace:
#0 /var/lib/symcon/modules/.store/de.nall.chan.xiaomi/Xiaomi Mi Device/module.php(184): XiaomiMiDevice->WriteValue('P_2_1', true)
#1 /-(3): XiaomiMiDevice->RequestAction('P_2_1', true)
#2 {main}
  thrown in /var/lib/symcon/modules/.store/de.nall.chan.xiaomi/Xiaomi Mi Device/module.php on line 304
 (Code: -32603)`

Discord probiere ich gerne, über den allg symcon Channel?

**Comment by Nall-chan** [comment]
Der Fehler sollte jetzt auch weg sein :)

**Comment by DarthWeber** [comment]
Richiutg. Super!
