### ISSUE TITLE
Feature request: left right

### ISSUE THREAD

**Issue by DarthWeber** [Nall-chan/Xiaomi#3]
Hi Michael,

meinst du, du könntest noch die Befehle "left", "right" einbauen? Damit lässt sich der Winkel manuell verstellen, ist vom Sofa ganz praktisch...

LG und danke,
Tom

**Comment by Nall-chan** [comment]
Welches Gerät?
Das hier?
https://home.miot-spec.com/spec/zhimi.fan.za4

Da gibt es keine Aktionen dafür laut den Specs. Also nein.

**Comment by DarthWeber** [comment]
laut den Specs nicht, aber die gibt es - zumindest über fhem geht das bisher auch. Willst du das einbauen, wenn ich das raushacke, oder möchtest du dich lieber auf die spec beschränken?

**Comment by Nall-chan** [comment]
Es gibt aktuell keine Geräte spezifischen Erweiterungen in dem Modul. Der Umfang (Statusvariablen und Profile inkl. Übersetzungen) wird durch die Specs in der Cloud definiert. Sonst müsste für jedes Model ein eigenes Modul bzw. eine eigene Definition von Hand gepflegt werden.
Das kann ich allein nicht leisten. Somit bleibt es aktuell auf die Specs beschränkt, bis diese vollumfänglich integriert sind (u.A. Aktionen fehlen noch).
Im weiteren Verlauf ist es dann eventuell möglich gerätespezifische Erweiterungen zu pflegen.

**Comment by Nall-chan** [comment]
Ergänzung:
Mein Fan hat dafür eine Eigenschaft.
![image](https://github.com/Nall-chan/Xiaomi/assets/12008505/bde88f6a-96e3-434d-acc6-cd2b3736afd5)
![image](https://github.com/Nall-chan/Xiaomi/assets/12008505/2f5c4137-fc56-49f5-959b-f788a84d578b)

**Comment by DarthWeber** [comment]
Meinst du, du kannst neben den via Cloud bezogenen Kommandos sowas machen wie benutzerdefinierte requests? Also wo man aus deinem Modul einfach eigene Kommandos senden kann?

Dann müsstest du nicht für jedes gerätspezifischen Sachen einbauen sondern dann könnte man das halt selbst ergänzen. Oder geht das schon mit den php Befehlen?

**Comment by Nall-chan** [comment]
Alles schon fertig. Aber dein links / rechts wird nicht gehen. Zumindest HA tricks und macht einfach bei Angle +1 / -1 😅
Das geht natürlich auch in Symcon, mit den Aktionen kannst du ja einfach + / - schalten.

**Comment by DarthWeber** [comment]
> Das geht natürlich auch in Symcon, mit den Aktionen kannst du ja einfach + / - schalten.

hab ich nicht kapiert. WIe sende ich denn z.B. PIID 6, String "left" oder so ?

**Comment by Nall-chan** [comment]
Gar nicht, wenn es nicht in den Specs steht.
Der zhimi.fan.za4 geht nur bis PID5.
PHP Funktionen sind fertig, aber bisher ohne Doku.
Kannst aber auch nur das senden was in den Specs steht.
```php
bool XIAOMI_WriteValueBoolean(int $InstanzID, int $ServiceId, int $PropertyId, bool $Value);
```
```php
XIAOMI_WriteValueInteger(<ID>, 2 , 1, true);
```

**Comment by DarthWeber** [comment]
Ah, schade. Ich nutze fhem nur noch, um den Fan zu bewegen und wollte das mal los werden. Irgendwie irre, von IPS zu fhem zu verbinden, nur um einen Fan zu bewegen.

Naja, vielleicht kommen ja irgendwann mal gerätespez. Erweiterungen.
