### ISSUE TITLE
Hostname statt IP

### ISSUE THREAD

**Issue by DarthWeber** [Nall-chan/Xiaomi#4]
Hi Michael,

könntest du in den Devices auch Hostnamen zulassen anstelle der IPs ? Leider ist das WLAN immer so eine Sache, im Winter gehen die Geräte in den Keller und bekommen dann im nächsten Sommer recht sicher eine andere IP ....

Danke,
Tom

**Comment by Nall-chan** [comment]
Das ist nicht möglich.
Da die IPv4 integraler Bestandteil der Protokolle ist.
Hostname werden dort nicht unterstützt.
Somit Reservierungen im DHCP Server vergeben, dann kann das Problem auch nicht auftreten.
