### ISSUE TITLE
Fehlermeldung 

### ISSUE THREAD

**Issue by dumdidum2000** [Nall-chan/Xiaomi#5]
Hallo,

ich habe alle 60 Sekunden 37 Fehlermeldungen in Symcon.

und alle sind identisch 

27.12.2023, 14:07:16 | Xiaomi MIoT Device   | Unknown error: -704220043

ich habe aber bis her auch keine Einschränkung gemerkt beim nutzen meiner geräte.

was kann ich machen um die abzustellen ?

Gruß

Robert

**Comment by Nall-chan** [comment]
Mir einen dump der Instanz zukommen lassen.
Außerdem ein paar Infos zum Geräte.
Idealerweise ein Screenshot der Instanz mit den Geräteinformationen.

Gerne auch per PN im Symcon Forum.
https://community.symcon.de/t/modul-xiaomi-miot-beta/135200?u=nall-chan

**Comment by dumdidum2000** [comment]
ok dann Wechsel ich zum Symcon forum
